name: search_movies
description: Search Movies App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  auto_route: ^7.2.0
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.4.0
  flutter_svg: ^2.0.6
  dio: ^5.1.2
  get_it: ^7.6.0
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  auto_route_generator: ^7.1.1

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
